varList.append(["TTDi","TTDi","DNN classifier t#bar{t} ll",[20,0,1],"LogY",["MoreY",1000],'IncludeOverflows'])
varList.append(["sigLDM","sigLDM","DNN classifier T1t^{4} Low DM",[20,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.9 < x < 1.0"]])
varList.append(["sigHDM","sigHDM","DNN classifier T1t^{4} High DM",[20,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.9 < x < 1.0"]])
varList.append(["WJ","WJ","DNN classifier W+jets",[20,0,1],"LogY",["MoreY",1000],'IncludeOverflows'])
varList.append(["TTS","TTS","DNN classifier t#bar{t} l",[20,0,1],"LogY",["MoreY",1000],'IncludeOverflows'])

varList.append(["sigLDM_100bins","sigLDM","DNN classifier T1t^{4} Low DM",[100,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigLDM_10bins","sigLDM","DNN classifier T1t^{4} Low DM",[10,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigLDM_20bins","sigLDM","DNN classifier T1t^{4} Low DM",[20,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigLDM_30bins","sigLDM","DNN classifier T1t^{4} Low DM",[30,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigLDM_40bins","sigLDM","DNN classifier T1t^{4} Low DM",[40,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigLDM_50bins","sigLDM","DNN classifier T1t^{4} Low DM",[50,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])

varList.append(["sigHDM_100bins","sigHDM","DNN classifier T1t^{4} High DM",[100,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigHDM_10bins","sigHDM","DNN classifier T1t^{4} High DM",[10,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigHDM_20bins","sigHDM","DNN classifier T1t^{4} High DM",[20,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigHDM_30bins","sigHDM","DNN classifier T1t^{4} High DM",[30,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigHDM_40bins","sigHDM","DNN classifier T1t^{4} High DM",[40,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])
varList.append(["sigHDM_50bins","sigHDM","DNN classifier T1t^{4} High DM",[50,0,1],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"0.90 < x < 1.0"]])

varList.append(["CatTT1Lep","(TTS >TTDi ) && (TTS >sigLDM)&& (TTS >sigHDM) && (TTS >WJ)","t#bar{t} l + jets Event Category",[2,0.0,2.0],"LogY",["MoreY",1000],'IncludeOverflows'])
varList.append(["CatTT2Lep","(TTDi > TTS) && (TTDi >sigLDM)&& (TTDi >sigHDM) && (TTDi >WJ )","t#bar{t} ll + jets Event Category",[2,0.0,2.0],"LogY",["MoreY",1000],'IncludeOverflows'])
varList.append(["CatWJ","(WJ >TTDi ) && (WJ >sigLDM)&& (WJ >sigHDM) && (WJ  > TTS )","W+jets Event Category",[2,0.0,2.0],"LogY",["MoreY",1000],'IncludeOverflows'])
varList.append(["CatSigLDM","(sigLDM >TTDi ) &&(sigLDM >sigHDM ) && (sigLDM >TTS) && (sigLDM >WJ)","T1t^{4} Low DM Event Category",[2,0.0,2.0],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"1.0 < x < 2.0"]])
varList.append(["CatSigHDM","(sigHDM >TTDi ) &&(sigHDM >sigLDM ) && (sigHDM >TTS) && (sigHDM >WJ)","T1t^{4} High DM Event Category",[2,0.0,2.0],"LogY",["MoreY",1000],'IncludeOverflows',['blinded',"1.0 < x < 2.0"]])
